<?php

namespace App\Actions\Admin\Showings;

use App\Showing;
use Carbon\Carbon;

class DeleteComingShowings
{
    /**
     * Delete old coming showings, because we will import them again.
     * A buffer of 10 minutes is used because the file generated by
     * the ticketing provider might be this old
     */
    public function __invoke(): void
    {
        $showings_start_after = Carbon::now()->modify('- 10 minutes');
        Showing::where('datetime', '>=', $showings_start_after)->delete();
    }
}
