<?php

namespace App\Jobs\Admin\Showings;

use App\Models\Showing;
use Carbon\Carbon;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;

class DeleteComingShowingsJob
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Execute the job.
     *
     * Delete old coming showings, because we will import them again.
     * A buffer of 10 minutes is used because the file generated by
     * the ticketing provider might be this old
     *
     * @return void
     */
    public function handle()
    {
        $showings_start_after = Carbon::now()->modify('- 10 minutes');
        Showing::where('datetime', '>=', $showings_start_after)->delete();
    }
}
